### ISSUE TITLE
App crashes after attempting to view media info

### ISSUE THREAD

**Issue by artificialparanoia** [Lmh170/Android-Gallery-App#46]
When attempting to view any media information via the Info button, the app instantly crashes. Custom build but up to date with main.

Debug log:

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221105.002/
package: com.example.gallery:1
process: com.example.gallery
processUptime: 3357 + 60 ms

java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2047)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1862)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1538)
	at com.example.gallery.ui.MainViewModel.getImageLocation(MainViewModel.kt:420)
	at com.example.gallery.ui.MainViewModel.performGetItemInfo(MainViewModel.kt:410)
	at com.example.gallery.ui.ViewPagerFrag.setUpViews$lambda$36(ViewPagerFrag.kt:302)
	at com.example.gallery.ui.ViewPagerFrag.$r8$lambda$nVQ5EKxE8vtG2zpntIfTkXUD2gw(Unknown Source:0)
	at com.example.gallery.ui.ViewPagerFrag$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by artificialparanoia** [comment]
So it seems as though (and this is evidenced by the log provided) that giving the app ACCESS_MEDIA_LOCATION seems to fix it, which I did [here](https://github.com/Lmh170/Android-Gallery-App/commit/bbb3d73d7181e70ad93bae5f9149c5bc90e4db75). It seems like there might be a better way to handle this through SAF picker stuff (is that applicable for metadata, though?), but I'm not particularly knowledgeable on what's possible with that, or how many permissions a secure/modern gallery app "should" have with this kind of functionality (whether it should be minimal or if certain permissions are required for usability/are expected for a system gallery app). The ASOP gallery app is not necessarily a good reference for that as it's old and therefore outdated, though it does support all of the expected system intents.

**Comment by artificialparanoia** [comment]
SAF may not exactly apply here (and according to Android documentation ACCESS_MEDIA_LOCATION is the "correct" method for Android 10 or higher), I'm just wondering if there are other methods for obtaining image metadata in a more secure way or if that was the intention due to the absence of anything requesting ACCESS_MEDIA_LOCATION for SDK 33. Strangest thing about it all is that adding the permission fixed some weird visual/process bugs when navigating away from MainActivity (to settings, video player, etc.), which seems very odd.
